# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='card',
            name='last_review_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='last review date'),
        ),
    ]
