# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20170201_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='back',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='card',
            name='front',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='card',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
